//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brevete
    {
        public int IdBrevete { get; set; }
        public int IdConductor { get; set; }
        public string Categoria { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaCaducidad { get; set; }
        public bool Vigencia { get; set; }
    
        public virtual Conductor Conductor { get; set; }
    }
}
